/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SupplierPortalRouteImport } from './routes/supplier-portal'

const AvlLazyRouteImport = createFileRoute('/avl')()
const ContractsLazyRouteImport = createFileRoute('/contracts')()
const ProcurementAiLazyRouteImport = createFileRoute('/procurement-ai')()
const SpendAnalyticsLazyRouteImport = createFileRoute('/spend-analytics')()
const FinanceBillingAndCashLazyRouteImport = createFileRoute(
  '/finance/billing-and-cash',
)()
const FinanceBudgetProLazyRouteImport = createFileRoute('/finance/budget-pro')()
const FinanceCashflowForecastingLazyRouteImport = createFileRoute(
  '/finance/cashflow-forecasting',
)()
const ProjectHseLazyRouteImport = createFileRoute('/project/hse')()
const ProjectPlanningLazyRouteImport = createFileRoute('/project/planning')()
const ProjectPortfolioCommandLazyRouteImport = createFileRoute(
  '/project/portfolio-command',
)()
const ProjectProject360LazyRouteImport = createFileRoute(
  '/project/project-360',
)()
const ProjectQualityLazyRouteImport = createFileRoute('/project/quality')()
const SalesDashboardLazyRouteImport = createFileRoute('/sales/dashboard')()
const SalesTenderPipelineLazyRouteImport = createFileRoute(
  '/sales/tender-pipeline',
)()
const SupplierPortalIndexLazyRouteImport =
  createFileRoute('/supplier-portal/')()
const SupplierPortalInvoicesLazyRouteImport = createFileRoute(
  '/supplier-portal/invoices',
)()
const SupplierPortalPurchaseOrdersLazyRouteImport = createFileRoute(
  '/supplier-portal/purchase-orders',
)()
const SupplierPortalQuotationsLazyRouteImport = createFileRoute(
  '/supplier-portal/quotations',
)()
const SupplierPortalRfqLazyRouteImport = createFileRoute(
  '/supplier-portal/rfq',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvlLazyRoute = AvlLazyRouteImport.update({
  id: '/avl',
  path: '/avl',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/avl.lazy').then((d) => d.Route))
const ContractsLazyRoute = ContractsLazyRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contracts.lazy').then((d) => d.Route))
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementAiLazyRoute = ProcurementAiLazyRouteImport.update({
  id: '/procurement-ai',
  path: '/procurement-ai',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/procurement-ai.lazy').then((d) => d.Route),
)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendAnalyticsLazyRoute = SpendAnalyticsLazyRouteImport.update({
  id: '/spend-analytics',
  path: '/spend-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/spend-analytics.lazy').then((d) => d.Route),
)
const SupplierPortalRoute = SupplierPortalRouteImport.update({
  id: '/supplier-portal',
  path: '/supplier-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBillingAndCashLazyRoute =
  FinanceBillingAndCashLazyRouteImport.update({
    id: '/billing-and-cash',
    path: '/billing-and-cash',
    getParentRoute: () => FinanceRoute,
  } as any).lazy(() =>
    import('./routes/finance.billing-and-cash.lazy').then((d) => d.Route),
  )
const FinanceBudgetProLazyRoute = FinanceBudgetProLazyRouteImport.update({
  id: '/budget-pro',
  path: '/budget-pro',
  getParentRoute: () => FinanceRoute,
} as any).lazy(() =>
  import('./routes/finance.budget-pro.lazy').then((d) => d.Route),
)
const FinanceCashflowForecastingLazyRoute =
  FinanceCashflowForecastingLazyRouteImport.update({
    id: '/cashflow-forecasting',
    path: '/cashflow-forecasting',
    getParentRoute: () => FinanceRoute,
  } as any).lazy(() =>
    import('./routes/finance.cashflow-forecasting.lazy').then((d) => d.Route),
  )
const ProjectHseLazyRoute = ProjectHseLazyRouteImport.update({
  id: '/hse',
  path: '/hse',
  getParentRoute: () => ProjectRoute,
} as any).lazy(() => import('./routes/project.hse.lazy').then((d) => d.Route))
const ProjectPlanningLazyRoute = ProjectPlanningLazyRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => ProjectRoute,
} as any).lazy(() =>
  import('./routes/project.planning.lazy').then((d) => d.Route),
)
const ProjectPortfolioCommandLazyRoute =
  ProjectPortfolioCommandLazyRouteImport.update({
    id: '/portfolio-command',
    path: '/portfolio-command',
    getParentRoute: () => ProjectRoute,
  } as any).lazy(() =>
    import('./routes/project.portfolio-command.lazy').then((d) => d.Route),
  )
const ProjectProject360LazyRoute = ProjectProject360LazyRouteImport.update({
  id: '/project-360',
  path: '/project-360',
  getParentRoute: () => ProjectRoute,
} as any).lazy(() =>
  import('./routes/project.project-360.lazy').then((d) => d.Route),
)
const ProjectQualityLazyRoute = ProjectQualityLazyRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => ProjectRoute,
} as any).lazy(() =>
  import('./routes/project.quality.lazy').then((d) => d.Route),
)
const SalesDashboardLazyRoute = SalesDashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SalesRoute,
} as any).lazy(() =>
  import('./routes/sales.dashboard.lazy').then((d) => d.Route),
)
const SalesTenderPipelineLazyRoute = SalesTenderPipelineLazyRouteImport.update({
  id: '/tender-pipeline',
  path: '/tender-pipeline',
  getParentRoute: () => SalesRoute,
} as any).lazy(() =>
  import('./routes/sales.tender-pipeline.lazy').then((d) => d.Route),
)
const SupplierPortalIndexLazyRoute = SupplierPortalIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupplierPortalRoute,
} as any).lazy(() =>
  import('./routes/supplier-portal.index.lazy').then((d) => d.Route),
)
const SupplierPortalInvoicesLazyRoute =
  SupplierPortalInvoicesLazyRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => SupplierPortalRoute,
  } as any).lazy(() =>
    import('./routes/supplier-portal.invoices.lazy').then((d) => d.Route),
  )
const SupplierPortalPurchaseOrdersLazyRoute =
  SupplierPortalPurchaseOrdersLazyRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => SupplierPortalRoute,
  } as any).lazy(() =>
    import('./routes/supplier-portal.purchase-orders.lazy').then(
      (d) => d.Route,
    ),
  )
const SupplierPortalQuotationsLazyRoute =
  SupplierPortalQuotationsLazyRouteImport.update({
    id: '/quotations',
    path: '/quotations',
    getParentRoute: () => SupplierPortalRoute,
  } as any).lazy(() =>
    import('./routes/supplier-portal.quotations.lazy').then((d) => d.Route),
  )
const SupplierPortalRfqLazyRoute = SupplierPortalRfqLazyRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => SupplierPortalRoute,
} as any).lazy(() =>
  import('./routes/supplier-portal.rfq.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/finance': typeof FinanceRouteWithChildren
  '/project': typeof ProjectRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/supplier-portal': typeof SupplierPortalRouteWithChildren
  '/avl': typeof AvlLazyRoute
  '/contracts': typeof ContractsLazyRoute
  '/procurement-ai': typeof ProcurementAiLazyRoute
  '/spend-analytics': typeof SpendAnalyticsLazyRoute
  '/finance/billing-and-cash': typeof FinanceBillingAndCashLazyRoute
  '/finance/budget-pro': typeof FinanceBudgetProLazyRoute
  '/finance/cashflow-forecasting': typeof FinanceCashflowForecastingLazyRoute
  '/project/hse': typeof ProjectHseLazyRoute
  '/project/planning': typeof ProjectPlanningLazyRoute
  '/project/portfolio-command': typeof ProjectPortfolioCommandLazyRoute
  '/project/project-360': typeof ProjectProject360LazyRoute
  '/project/quality': typeof ProjectQualityLazyRoute
  '/sales/dashboard': typeof SalesDashboardLazyRoute
  '/sales/tender-pipeline': typeof SalesTenderPipelineLazyRoute
  '/supplier-portal/invoices': typeof SupplierPortalInvoicesLazyRoute
  '/supplier-portal/purchase-orders': typeof SupplierPortalPurchaseOrdersLazyRoute
  '/supplier-portal/quotations': typeof SupplierPortalQuotationsLazyRoute
  '/supplier-portal/rfq': typeof SupplierPortalRfqLazyRoute
  '/supplier-portal/': typeof SupplierPortalIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/finance': typeof FinanceRouteWithChildren
  '/project': typeof ProjectRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/avl': typeof AvlLazyRoute
  '/contracts': typeof ContractsLazyRoute
  '/procurement-ai': typeof ProcurementAiLazyRoute
  '/spend-analytics': typeof SpendAnalyticsLazyRoute
  '/finance/billing-and-cash': typeof FinanceBillingAndCashLazyRoute
  '/finance/budget-pro': typeof FinanceBudgetProLazyRoute
  '/finance/cashflow-forecasting': typeof FinanceCashflowForecastingLazyRoute
  '/project/hse': typeof ProjectHseLazyRoute
  '/project/planning': typeof ProjectPlanningLazyRoute
  '/project/portfolio-command': typeof ProjectPortfolioCommandLazyRoute
  '/project/project-360': typeof ProjectProject360LazyRoute
  '/project/quality': typeof ProjectQualityLazyRoute
  '/sales/dashboard': typeof SalesDashboardLazyRoute
  '/sales/tender-pipeline': typeof SalesTenderPipelineLazyRoute
  '/supplier-portal/invoices': typeof SupplierPortalInvoicesLazyRoute
  '/supplier-portal/purchase-orders': typeof SupplierPortalPurchaseOrdersLazyRoute
  '/supplier-portal/quotations': typeof SupplierPortalQuotationsLazyRoute
  '/supplier-portal/rfq': typeof SupplierPortalRfqLazyRoute
  '/supplier-portal': typeof SupplierPortalIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/finance': typeof FinanceRouteWithChildren
  '/project': typeof ProjectRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/supplier-portal': typeof SupplierPortalRouteWithChildren
  '/avl': typeof AvlLazyRoute
  '/contracts': typeof ContractsLazyRoute
  '/procurement-ai': typeof ProcurementAiLazyRoute
  '/spend-analytics': typeof SpendAnalyticsLazyRoute
  '/finance/billing-and-cash': typeof FinanceBillingAndCashLazyRoute
  '/finance/budget-pro': typeof FinanceBudgetProLazyRoute
  '/finance/cashflow-forecasting': typeof FinanceCashflowForecastingLazyRoute
  '/project/hse': typeof ProjectHseLazyRoute
  '/project/planning': typeof ProjectPlanningLazyRoute
  '/project/portfolio-command': typeof ProjectPortfolioCommandLazyRoute
  '/project/project-360': typeof ProjectProject360LazyRoute
  '/project/quality': typeof ProjectQualityLazyRoute
  '/sales/dashboard': typeof SalesDashboardLazyRoute
  '/sales/tender-pipeline': typeof SalesTenderPipelineLazyRoute
  '/supplier-portal/invoices': typeof SupplierPortalInvoicesLazyRoute
  '/supplier-portal/purchase-orders': typeof SupplierPortalPurchaseOrdersLazyRoute
  '/supplier-portal/quotations': typeof SupplierPortalQuotationsLazyRoute
  '/supplier-portal/rfq': typeof SupplierPortalRfqLazyRoute
  '/supplier-portal/': typeof SupplierPortalIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/finance'
    | '/project'
    | '/sales'
    | '/supplier-portal'
    | '/avl'
    | '/contracts'
    | '/procurement-ai'
    | '/spend-analytics'
    | '/finance/billing-and-cash'
    | '/finance/budget-pro'
    | '/finance/cashflow-forecasting'
    | '/project/hse'
    | '/project/planning'
    | '/project/portfolio-command'
    | '/project/project-360'
    | '/project/quality'
    | '/sales/dashboard'
    | '/sales/tender-pipeline'
    | '/supplier-portal/invoices'
    | '/supplier-portal/purchase-orders'
    | '/supplier-portal/quotations'
    | '/supplier-portal/rfq'
    | '/supplier-portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/finance'
    | '/project'
    | '/sales'
    | '/avl'
    | '/contracts'
    | '/procurement-ai'
    | '/spend-analytics'
    | '/finance/billing-and-cash'
    | '/finance/budget-pro'
    | '/finance/cashflow-forecasting'
    | '/project/hse'
    | '/project/planning'
    | '/project/portfolio-command'
    | '/project/project-360'
    | '/project/quality'
    | '/sales/dashboard'
    | '/sales/tender-pipeline'
    | '/supplier-portal/invoices'
    | '/supplier-portal/purchase-orders'
    | '/supplier-portal/quotations'
    | '/supplier-portal/rfq'
    | '/supplier-portal'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/finance'
    | '/project'
    | '/sales'
    | '/supplier-portal'
    | '/avl'
    | '/contracts'
    | '/procurement-ai'
    | '/spend-analytics'
    | '/finance/billing-and-cash'
    | '/finance/budget-pro'
    | '/finance/cashflow-forecasting'
    | '/project/hse'
    | '/project/planning'
    | '/project/portfolio-command'
    | '/project/project-360'
    | '/project/quality'
    | '/sales/dashboard'
    | '/sales/tender-pipeline'
    | '/supplier-portal/invoices'
    | '/supplier-portal/purchase-orders'
    | '/supplier-portal/quotations'
    | '/supplier-portal/rfq'
    | '/supplier-portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  ProjectRoute: typeof ProjectRouteWithChildren
  SalesRoute: typeof SalesRouteWithChildren
  SupplierPortalRoute: typeof SupplierPortalRouteWithChildren
  AvlLazyRoute: typeof AvlLazyRoute
  ContractsLazyRoute: typeof ContractsLazyRoute
  ProcurementAiLazyRoute: typeof ProcurementAiLazyRoute
  SpendAnalyticsLazyRoute: typeof SpendAnalyticsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avl': {
      id: '/avl'
      path: '/avl'
      fullPath: '/avl'
      preLoaderRoute: typeof AvlLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement-ai': {
      id: '/procurement-ai'
      path: '/procurement-ai'
      fullPath: '/procurement-ai'
      preLoaderRoute: typeof ProcurementAiLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spend-analytics': {
      id: '/spend-analytics'
      path: '/spend-analytics'
      fullPath: '/spend-analytics'
      preLoaderRoute: typeof SpendAnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-portal': {
      id: '/supplier-portal'
      path: '/supplier-portal'
      fullPath: '/supplier-portal'
      preLoaderRoute: typeof SupplierPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/billing-and-cash': {
      id: '/finance/billing-and-cash'
      path: '/billing-and-cash'
      fullPath: '/finance/billing-and-cash'
      preLoaderRoute: typeof FinanceBillingAndCashLazyRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/budget-pro': {
      id: '/finance/budget-pro'
      path: '/budget-pro'
      fullPath: '/finance/budget-pro'
      preLoaderRoute: typeof FinanceBudgetProLazyRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/cashflow-forecasting': {
      id: '/finance/cashflow-forecasting'
      path: '/cashflow-forecasting'
      fullPath: '/finance/cashflow-forecasting'
      preLoaderRoute: typeof FinanceCashflowForecastingLazyRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/project/hse': {
      id: '/project/hse'
      path: '/hse'
      fullPath: '/project/hse'
      preLoaderRoute: typeof ProjectHseLazyRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/project/planning': {
      id: '/project/planning'
      path: '/planning'
      fullPath: '/project/planning'
      preLoaderRoute: typeof ProjectPlanningLazyRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/project/portfolio-command': {
      id: '/project/portfolio-command'
      path: '/portfolio-command'
      fullPath: '/project/portfolio-command'
      preLoaderRoute: typeof ProjectPortfolioCommandLazyRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/project/project-360': {
      id: '/project/project-360'
      path: '/project-360'
      fullPath: '/project/project-360'
      preLoaderRoute: typeof ProjectProject360LazyRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/project/quality': {
      id: '/project/quality'
      path: '/quality'
      fullPath: '/project/quality'
      preLoaderRoute: typeof ProjectQualityLazyRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/sales/dashboard': {
      id: '/sales/dashboard'
      path: '/dashboard'
      fullPath: '/sales/dashboard'
      preLoaderRoute: typeof SalesDashboardLazyRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/tender-pipeline': {
      id: '/sales/tender-pipeline'
      path: '/tender-pipeline'
      fullPath: '/sales/tender-pipeline'
      preLoaderRoute: typeof SalesTenderPipelineLazyRouteImport
      parentRoute: typeof SalesRoute
    }
    '/supplier-portal/': {
      id: '/supplier-portal/'
      path: '/'
      fullPath: '/supplier-portal/'
      preLoaderRoute: typeof SupplierPortalIndexLazyRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/invoices': {
      id: '/supplier-portal/invoices'
      path: '/invoices'
      fullPath: '/supplier-portal/invoices'
      preLoaderRoute: typeof SupplierPortalInvoicesLazyRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/purchase-orders': {
      id: '/supplier-portal/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/supplier-portal/purchase-orders'
      preLoaderRoute: typeof SupplierPortalPurchaseOrdersLazyRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/quotations': {
      id: '/supplier-portal/quotations'
      path: '/quotations'
      fullPath: '/supplier-portal/quotations'
      preLoaderRoute: typeof SupplierPortalQuotationsLazyRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/rfq': {
      id: '/supplier-portal/rfq'
      path: '/rfq'
      fullPath: '/supplier-portal/rfq'
      preLoaderRoute: typeof SupplierPortalRfqLazyRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
  }
}

interface FinanceRouteChildren {
  FinanceBillingAndCashLazyRoute: typeof FinanceBillingAndCashLazyRoute
  FinanceBudgetProLazyRoute: typeof FinanceBudgetProLazyRoute
  FinanceCashflowForecastingLazyRoute: typeof FinanceCashflowForecastingLazyRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceBillingAndCashLazyRoute: FinanceBillingAndCashLazyRoute,
  FinanceBudgetProLazyRoute: FinanceBudgetProLazyRoute,
  FinanceCashflowForecastingLazyRoute: FinanceCashflowForecastingLazyRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface ProjectRouteChildren {
  ProjectHseLazyRoute: typeof ProjectHseLazyRoute
  ProjectPlanningLazyRoute: typeof ProjectPlanningLazyRoute
  ProjectPortfolioCommandLazyRoute: typeof ProjectPortfolioCommandLazyRoute
  ProjectProject360LazyRoute: typeof ProjectProject360LazyRoute
  ProjectQualityLazyRoute: typeof ProjectQualityLazyRoute
}

const ProjectRouteChildren: ProjectRouteChildren = {
  ProjectHseLazyRoute: ProjectHseLazyRoute,
  ProjectPlanningLazyRoute: ProjectPlanningLazyRoute,
  ProjectPortfolioCommandLazyRoute: ProjectPortfolioCommandLazyRoute,
  ProjectProject360LazyRoute: ProjectProject360LazyRoute,
  ProjectQualityLazyRoute: ProjectQualityLazyRoute,
}

const ProjectRouteWithChildren =
  ProjectRoute._addFileChildren(ProjectRouteChildren)

interface SalesRouteChildren {
  SalesDashboardLazyRoute: typeof SalesDashboardLazyRoute
  SalesTenderPipelineLazyRoute: typeof SalesTenderPipelineLazyRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesDashboardLazyRoute: SalesDashboardLazyRoute,
  SalesTenderPipelineLazyRoute: SalesTenderPipelineLazyRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

interface SupplierPortalRouteChildren {
  SupplierPortalInvoicesLazyRoute: typeof SupplierPortalInvoicesLazyRoute
  SupplierPortalPurchaseOrdersLazyRoute: typeof SupplierPortalPurchaseOrdersLazyRoute
  SupplierPortalQuotationsLazyRoute: typeof SupplierPortalQuotationsLazyRoute
  SupplierPortalRfqLazyRoute: typeof SupplierPortalRfqLazyRoute
  SupplierPortalIndexLazyRoute: typeof SupplierPortalIndexLazyRoute
}

const SupplierPortalRouteChildren: SupplierPortalRouteChildren = {
  SupplierPortalInvoicesLazyRoute: SupplierPortalInvoicesLazyRoute,
  SupplierPortalPurchaseOrdersLazyRoute: SupplierPortalPurchaseOrdersLazyRoute,
  SupplierPortalQuotationsLazyRoute: SupplierPortalQuotationsLazyRoute,
  SupplierPortalRfqLazyRoute: SupplierPortalRfqLazyRoute,
  SupplierPortalIndexLazyRoute: SupplierPortalIndexLazyRoute,
}

const SupplierPortalRouteWithChildren = SupplierPortalRoute._addFileChildren(
  SupplierPortalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FinanceRoute: FinanceRouteWithChildren,
  ProjectRoute: ProjectRouteWithChildren,
  SalesRoute: SalesRouteWithChildren,
  SupplierPortalRoute: SupplierPortalRouteWithChildren,
  AvlLazyRoute: AvlLazyRoute,
  ContractsLazyRoute: ContractsLazyRoute,
  ProcurementAiLazyRoute: ProcurementAiLazyRoute,
  SpendAnalyticsLazyRoute: SpendAnalyticsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
